### ISSUE TITLE
Error while deploy

### ISSUE THREAD

**Issue by ivan-exness** [vmware/photon-controller#16]
I have Install 3 nested esxi 6u2 into my vcenter cloud. 
Enabled SSH Access.
Download and deploy install-vm.ova
Open web console and configure next
```
hosts:
  - metadata:
      MANAGEMENT_DATASTORE: datastore1
      MANAGEMENT_PORTGROUP: VM Network
      MANAGEMENT_NETWORK_NETMASK: 255.255.255.0
      MANAGEMENT_NETWORK_DNS_SERVER: 192.168.137.1
      MANAGEMENT_NETWORK_GATEWAY: 192.168.137.1
      MANAGEMENT_VM_IPS: 192.168.137.11
    address_ranges: 192.168.137.98
    username: root
    password: esxcloud
    usage_tags:
      - CLOUD
      - MGMT
  - metadata:
      MANAGEMENT_DATASTORE: datastore1
      MANAGEMENT_PORTGROUP: VM Network
      MANAGEMENT_NETWORK_NETMASK: 255.255.255.0
      MANAGEMENT_NETWORK_DNS_SERVER: 192.168.137.1
      MANAGEMENT_NETWORK_GATEWAY: 192.168.137.1
      MANAGEMENT_VM_IPS: 192.168.137.12
    address_ranges: 192.168.137.103
    username: root
    password: esxcloud
    usage_tags:
      - CLOUD
      - MGMT
  - metadata:
      MANAGEMENT_DATASTORE: datastore1
      MANAGEMENT_PORTGROUP: VM Network
      MANAGEMENT_NETWORK_NETMASK: 255.255.255.0
      MANAGEMENT_NETWORK_DNS_SERVER: 192.168.137.1
      MANAGEMENT_NETWORK_GATEWAY: 192.168.137.1
      MANAGEMENT_VM_IPS: 192.168.137.13
    address_ranges: 192.168.137.194
    username: root
    password: esxcloud
    usage_tags:
      - CLOUD
      - MGMT
deployment:
  image_datastores:
    - datastore1
  auth_enabled: false
  stats_enabled: false
  use_image_datastore_for_vms: false
  loadbalancer_enabled: true

```

But after click Deploy I have instantly error
Error : -
![screenshot 2016-03-28 11 31 58](https://cloud.githubusercontent.com/assets/17728801/14074416/60044190-f4d9-11e5-842c-dcbc38296771.png)
