### ISSUE TITLE
ESXi Installer OVA: Support for dvSwitches/Portgroups

### ISSUE THREAD

**Issue by pdellaert** [vmware/photon-controller#19]
As far as i can tell, whenever i try to deploy the controller VM through the ESXi way of working and i use a Portgroup on a dvSwitch, it can not attach the controllers nic to the portgroup. 

I have to follow the deployment and once the VM is deployed, i need to manually reconfigure the NIC.

config yaml:
```
hosts:
  - metadata:
      MANAGEMENT_DATASTORE: esxi1
      MANAGEMENT_PORTGROUP: NPI-Management
      MANAGEMENT_NETWORK_NETMASK: 255.0.0.0
      MANAGEMENT_NETWORK_DNS_SERVER: 10.189.2.254
      MANAGEMENT_NETWORK_GATEWAY: 10.0.0.1
      MANAGEMENT_VM_IPS: 10.189.2.71
    address_ranges: 10.189.2.11
    username: root
    password: esxcloud
    usage_tags:
      - CLOUD
      - MGMT
deployment:
  image_datastores:
    - esxi1
  auth_enabled: false
  stats_enabled: false
  ntp_endpoint: 10.189.2.254
  use_image_datastore_for_vms: true
  loadbalancer_enabled: true
```
