### ISSUE TITLE
Encountering NotEnoughMemoryResource even when overriding vm settings

### ISSUE THREAD

**Issue by ebauman** [vmware/photon-controller#54]
Greetings,

I am attempting to deploy photon controller to a small 4-host cluster.
I have overridden the memory, cpu, and disk resource settings in the yaml configuration file before attempting to deploy.
Here is a snippet of the settings from one host:

```
hosts:
  - metadata:
      MANAGEMENT_DATASTORE: Production Capacity
      MANAGEMENT_PORTGROUP: Test01-440
      MANAGEMENT_NETWORK_NETMASK: 255.255.255.0
      MANAGEMENT_NETWORK_DNS_SERVER: 192.168.1.254
      MANAGEMENT_NETWORK_GATEWAY: 192.168.1.254
      MANAGEMENT_VM_IPS: 192.168.1.1
      MANAGEMENT_VM_CPU_COUNT_OVERWRITE: 2
      MANAGEMENT_VM_MEMORY_MB_OVERWRITE: 2048
      MANAGEMENT_VM_DISK_GB_OVERWRITE: 20
```

When I attempt to deploy, the deployment process runs for several minutes before I receive the following error:

`API Errors: [photon: { HTTP status: '0', code: 'DeploymentFailed', message: 'Deployment #361ec03f-8edf-4db3-b4ed-4c064d92e678 failed: [Task "CREATE_VM": step "RESERVE_RESOURCE" failed with error code "NotEnoughMemoryResource", message "null"]', data: 'map[id:361ec03f-8edf-4db3-b4ed-4c064d92e678 error:[Task "CREATE_VM": step "RESERVE_RESOURCE" failed with error code "NotEnoughMemoryResource", message "null"]]' }]`

All of the hosts in question have at least 24GB of free memory, and as I am (theoretically) only requesting 2G, I think something might be wrong here. 

I am using photon-controller version 1.0TP2, photon CLI 63a4889.
