### ISSUE TITLE
Photon installer fails to delete system deployment

### ISSUE THREAD

**Issue by medvedzver** [vmware/photon-controller#76]
Hi!

I have Photon Installer and I'm deploying photon controller using 
`photon system deploy manifest.yml`.
Deployment fails because I have the same IP in `addresses_range` in both metadata entries. 
`photon system destroy` succeeded. 

I remove IP address in second `metadata.addresses_range` and do `photon system deploy manifest.yml`.
Deployment fails.

Now I try to do `photon system destroy` and task hangs. I can't delete system deployment and if I cancel a task (ctrl+c) I can't do system destroy because task is in error state.

Could you please tell me how to delete a failing task in PhotonInstaller? I can constantly reproduce an issue - and issue is only for the second failed deployment. 

Here is console output:
```
user$ photon system deploy photon_deploy.yml
Using target 'http://192.168.218.101:9000'
Created deployment 8f40c847542ca2e0e9968
Host with ip '192.168.218.100' created: ID = 8f40c847542ca2e1878c0
2017/01/04 09:16:35 Error: photon: Task '8f40c847542ca2eb99ac0' is in error state: {@step=={"sequence"=>"1","state"=>"ERROR","errors"=>[photon: { HTTP status: '0', code: 'DuplicateHost', message: 'Host with IP Found existing HostService entity with the same hostAddress 192.168.218.100 already registered.', data: 'map[ip:Found existing HostService entity with the same hostAddress 192.168.218.100]' }],"warnings"=>[],"operation"=>"QUERY_HOST_TASK_RESULT","startedTime"=>"1480811018326","queuedTime"=>"1480811018301","endTime"=>"1480811023349","options"=>map[]}}
API Errors: [photon: { HTTP status: '0', code: 'DuplicateHost', message: 'Host with IP Found existing HostService entity with the same hostAddress 192.168.218.100 already registered.', data: 'map[ip:Found existing HostService entity with the same hostAddress 192.168.218.100]' }]

user$ photon system destroy
Using target 'http://192.168.218.101:9000'
Deployment '8f40c847542ca2e0e9968' is destroyed.
Host has been deleted: ID = 8f40c847542ca2e1878c0
Host has been deleted: ID = 8f40c847542ca2eb98743
Deleted deployment 8f40c847542ca2e0e9968

user$ photon system deploy photon_deploy.yml
Using target 'http://192.168.218.101:9000'
Created deployment 8f40c847542ca4a4944c0
2017/01/04 09:24:12 Error: Bad IP Address defined in DC Map

user$ photon system destroy
Using target 'http://192.168.218.101:9000'
 0h21m53s [=== ] DESTROY_DEPLOYMENT : DEPROVISION_HOSTS | Step 3/3
2017/01/04 09:54:31 Error: Timed out while waiting for task to complete
```
Here is manifest: 
```
hosts:
- metadata:
    MANAGEMENT_DATASTORE: datastore2
    MANAGEMENT_PORTGROUP: VM Network
    MANAGEMENT_NETWORK_NETMASK: 255.255.255.0
    MANAGEMENT_NETWORK_DNS_SERVER: 192.168.218.2
    MANAGEMENT_NETWORK_GATEWAY: 192.168.218.1
    MANAGEMENT_VM_IPS: 192.168.218.33 #PC pi
  address_ranges: 192.168.218.100
  username: root
  password: hohoho 
  usage_tags:
    - CLOUD
    - MGMT
- metadata:
    ALLOWED_SERVICES: Lightwave
    MANAGEMENT_DATASTORE: lightwave
    MANAGEMENT_PORTGROUP: VM Network
    MANAGEMENT_NETWORK_NETMASK: 255.255.255.0
    MANAGEMENT_NETWORK_DNS_SERVER: 192.168.218.2
    MANAGEMENT_NETWORK_GATEWAY: 192.168.218.1
    MANAGEMENT_VM_IPS: 192.168.218.201 #PC pi
  address_ranges: 192.168.218.200
  username: root
  password: hohoho 
  usage_tags:
    - CLOUD
    - MGMT
deployment:
  resume_system: true
  image_datastores:
    - datastore2
    - lightwave
  use_image_datastore_for_vms: true
  loadbalancer_enabled: false
  ntp_endpoint: pool.ntp.org
  auth_enabled: true
  oauth_tenant: esxcloud
  oauth_username: admin
  oauth_password: admin
  oauth_security_groups:
  - "esxcloud\\Administrators"
  - "esxcloud\\photonControllerAdmins"
  sdn_enabled: false
  stats_enabled: false
  loadbalancer_enabled: false
```

Side question - AFAIK when deployment succeeded I wouldn't be able to connect to PC because you've restricted ssh access with well known password (as AlianRoy says [here](https://github.com/vmware/photon-controller/issues/72). Can you please tell me how to specify my public/private key for PC so I can ssh to it? Couldn't find it in docs. 

Thanks!
