### ISSUE TITLE
Default Storage Class to support Kubernetes 1.6 on Photon Platform with persistent volume

### ISSUE THREAD

**Issue by luomiao** [vmware/photon-controller#91]
Original Issue:
https://github.com/kubernetes/kubernetes/issues/40072

Since the installation of kubernetes cluster on Photon Controller is part of the cluster management code in https://github.com/vmware/photon-controller, in order to have the default storage class started by addons manager, the following changes are required on the Photon Controller side during the kubernetes cluster initialization process:

1. Create a flavor with default parameters with “--kind persistent-disk” and “--name k8s-default-persis-disk-[SOME ID]”

2. Generate a yaml file under /etc/kubernetes/addons on master nodes:

```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: default
annotations:
  storageclass.beta.kubernetes.io/is-default-class: "true"
labels:
  kubernetes.io/cluster-service: "true"
provisioner:
  kubernetes.io/photon
parameters:
  flavor: k8s-default-persis-disk-[SOME ID]
```

@AlainRoy @ashoksekar07
