### ISSUE TITLE
Secret handling Pod for kubernetes on authentication-enabled Photon Platform 

### ISSUE THREAD

**Issue by luomiao** [vmware/photon-controller#92]
I am not sure if this is the right place to track this issue...

Skip the discussion of the reason, now we will need a secret handling pod running on the master nodes, in order to achieve a compromise of user experience and authentication.

1. The pod can be started either as a static pod or by the user, before running any other pods with storage operations. 
2. Users are responsible to create a secret which includes login information.
3. The docker image of this secret handling pod should be stored under docker.io/vmware/
4. Need instructions for users to execute necessary steps. If the pod will be created by the users, a yaml file should be provided too.

The Dockerfile for the image:

```
FROM vmware/photon:1.0

RUN tdnf install -y sed wget && \
    wget http://stedolan.github.io/jq/download/linux64/jq -O /usr/bin/jq && chmod +x /usr/bin/jq && \
    mkdir /var/photon

COPY update-config.sh /var/photon/

WORKDIR /var/photon
ENTRYPOINT ["/var/photon/update-config.sh"]
```

update-config.sh:
```
#!/bin/bash
# Script that runs in Pod and updates $PHOTON_CONF_FILE with username/passwrod
# which are retrieved from Kubernetes API server as secret.
# User is responsible for creating a secret called 'photon-keys' with username/password in it.
# Following is the example of commands to create such a secret.
#     echo "admin" > username
#     echo "password" > password
#     kubectl create secret generic photon-keys --from-file=./username --from-file=./password
# As soon as secret is created, this script will fetch the secret
# and update the $PHOTON_CONF_FILE with it.

PHOTON_LOGIN_FILE="/etc/kubernetes/pc_login_info"

KUBE_TOKEN=""
username=""
password=""
WAIT=10

while true
do
  response=$(curl -sSk https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/default/secrets/photon-keys)
  username=$(echo $response | jq '.data.username' | tr -d '"' | base64 --decode)
  password=$(echo $response | jq '.data.password' | tr -d '"' | base64 --decode)

  if [ "$username" == "null" ]; then
    echo "Username not found in secret."
    sleep $WAIT
    continue
  fi

  if [ "$password" == "null" ]; then
    echo "Password not found in secret."
    sleep $WAIT
    continue
  fi

  # Update the photon config file with username/password

  echo "$username" > $PHOTON_LOGIN_FILE
  echo "$password" >> $PHOTON_LOGIN_FILE

  echo "Updated photon config file. Sleeping for $WAIT seconds."
  sleep $WAIT
done
```

YAML file:
```
apiVersion: v1
kind: Pod
metadata:
  name: photon-conf
spec:
  containers:
  - name: photon-kube-conf
    image: vmware/photon-kube-conf:latest
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: photon-conf-volume
  volumes:
  - name: photon-conf-volume
    hostPath:
      # directory location on host
      path: /etc/kubernetes
```

@AlainRoy @ashoksekar07
